- app.js
- controllers/userController.js
- database/connection.js
- database/models/productModel.js
- database/models/userModel.js
- package-lock.json
- package.json
- routes/userRouter.js
> [Feat] Add source base

- controllers/userController.js
- database/models/userModel.js
- routes/userRouter.js
> [Feat] Add API user detail :wrench:

- app.js
- controllers/userController.js
- middlewares/authJWT.js
- middlewares/verifyJWT.js
- routes/userRouter.js
If have token: 
If dont have token or wrong token:
> [Feat] Handle auth token

- app.js
- controllers/assetsController.js
- controllers/orderController.js
- controllers/typeController.js
- database/models/orderItemModel.js
- database/models/orderModel.js
- database/models/productModel.js
- database/models/statusModel.js
- routes/assetsRouter.js
- routes/orderRouter.js
- routes/typeRouter.js
> Complete function's Type

- controllers/middleware/index.js
- controllers/middleware/middlewareController.js
- controllers/userController.js
- database/models/middlewares/index.js
- database/models/middlewares/refreshToken.js
- database/models/userModel.js
- middlewares/index.js
- middlewares/refreshToken.js
> [Feat] Add verify token, config refreshtoken

- app.js
- controllers/orderController.js
- database/models/orderItemModel.js
- database/models/orderModel.js
- database/models/productModel.js
- database/models/statusModel.js
- package.json
- routes/orderRouter.js
add order
get order
and fix the product Model: add the amount to the product Model
> [ Fix ] : OrderController , Model: OrderItem, Order, Status, Product and OrderRouter

- app.js
- controllers/addressController.js
- controllers/assetsController.js
- controllers/districtController.js
- controllers/feedbackController.js
- controllers/feedbackReplyController.js
- controllers/productController.js
- controllers/proviceController.js
- controllers/townController.js
- controllers/typeController.js
- database/connection.js
- database/models/addressModel.js
- database/models/assetsModel.js
- database/models/districtModel.js
- database/models/feedbackModel.js
- database/models/feedbackReplyModel.js
- database/models/productModel.js
- database/models/townModel.js
- database/models/userModel.js
- package.json
- routes/addressRouter.js
- routes/assetsRouter.js
- routes/districtRouter.js
- routes/feedbackReplyRouter.js
- routes/feedbackRouter.js
- routes/productRouter.js
- routes/proviceRouter.js
- routes/townRouter.js
- routes/typeRouter.js
Add typeController
Add assetsConroller
AddProduct & UpdateProduct in productController
> [WIP]add and update product

- database/models/productModel.js
- database/models/typeModel.js
Delete amount in productModel
Create amount in typeModel
> fix product model

- controllers/typeCtrl.js
- models/productModel.js
- models/typeModel.js
- routes/typeRouter.js
- server.js
> [FEAT] Create Type

- controllers/feedback/feedbackCtrl.js
- controllers/order/orderCtrl.js
- controllers/productCtrl.js
- controllers/typeCtrl.js
- models/productModel.js
- models/typeModel.js
- routes/orderRouter.js
add check Number of product availble in store
add function update Order
> Create function updateOrder and fix funtion addOrder

- controllers/productCtrl.js
- models/productModel.js
- routes/productRouter.js
```json
{
"title": "Com cho meo an",
"description": "Com dac biet nhap khau tu My Tho",
"amount": 20,
"price": "20000",
"types": [
{   
"name": "XL",
"price": 20,
"amount": 20
},
{
"name": "XL",
"price": 20,
"amount": 20
}
],
"images": {
"public_id": "test/f3vcw65s41ymkw9xg4ju",
"url": "https://petshopsaigon.vn/wp-content/uploads/2021/03/thuc-an-cho-meo-con-me-o-kitten-11kg-1.jpg"
},
"category": "Meo"
}
```
> [Fix]: Refactor Product type

- controllers/order/orderCtrl.js
- controllers/userCtrl.js
- middleware/authMe.js
- models/userModel.js
- routes/orderRouter.js
> Sửa user_id trong order
> Return userid from token
```js
const authMe = require('../../middleware/authMe');
const user_id = await authMe(req);
```
> [Feat]: return user id from token :rocket:

- controllers/feedback/feedbackCtrl.js
- controllers/order/orderCtrl.js
- controllers/productCtrl.js
- models/detailProductModel.js
- models/feedback/feedbackModel.js
- models/feedback/replyFeedbackModel.js
- models/productModel.js
- routes/productRouter.js
- create feeback and reply feedback
- create detail product
- fix model product
> @duyen/product detail

- .gitignore
- controllers/order/orderCtrl.js
- controllers/productCtrl.js
- models/productModel.js
- routes/orderRouter.js
```js
{
"orderItems": [
{
"product_id": "63789837b20fd14378719918",
"amount": 2,
"type_id": "63789837b20fd14378719913"
},    
{
"product_id": "63789837b20fd14378719918",
"amount": 3,
"type_id": "63789837b20fd14378719914"
}
],
"address": "100 Nguyen Luong Bang",
"phone": "0123456789",
"shippingCode": "11501000fgdgfd",
"user": "6337d686a10f308532677cff"
}
```
> [Feat]: Update amount product

- controllers/order/orderCtrl.js
- routes/orderRouter.js
```json
{
"product_id":"63789837b20fd14378719918",
"type_id":"63789837b20fd14378719914",
"amount":2
}
```
> [Feat] Add image to order

- controllers/feedback/feedbackCtrl.js
- controllers/userCtrl.js
- models/feedback/feedbackModel.js
- routes/feedbackRouter.js
```json
{
"content": "Sản phẩm bịp qua",
"image_url": "https://thigiacmaytinh.com/wp-content/uploads/2020/04/tranparent_dog.jpg",
"rating": 1,
"product_id": "63818d9bcacd0900049d7b66"
}
```
> [Fix] Fix feedback

- controllers/order/orderCtrl.js
- controllers/order/paypalCtrl.js
- routes/orderRouter.js
``` json
{
"start": "2021-10-29T13:56:42.408+00:00",
"end": "2023-11-29T13:56:42.408+00:00"
}
```
``` json
[
{
"total": 2150,
"listOrderItems": [
{
"product_id": "638abf8c76cd6840a439fa61",
"type_id": "638abf8c76cd6840a439fa5f",
"amount": 25,
"image": "https://petshopsaigon.vn/wp-content/uploads/2021/03/thuc-an-cho-meo-con-me-o-kitten-11kg-1.jpg",
"product_name": "Do uong cho cho va meo",
"price": 80,
"type_name": "L"
},
{
"product_id": "638abf8c76cd6840a439fa61",
"type_id": "638abf8c76cd6840a439fa5e",
"amount": 1,
"image": "https://petshopsaigon.vn/wp-content/uploads/2021/03/thuc-an-cho-meo-con-me-o-kitten-11kg-1.jpg",
"product_name": "Do uong cho cho va meo",
"price": 50,
"type_name": "S"
},
{
"product_id": "63818e20cacd0900049d7b6f",
"type_id": "63818e20cacd0900049d7b6c",
"amount": 5, …
```
> [Feat] Order dashboard

- controllers/userCtrl.js
- models/userModel.js
- routes/userRouter.js
Request body:
``` json
{
"pet": [
"Dog",
"Cat"
],
"birthday": "2022-12-15T13:49:23.342Z",
"sex":"false",
"fullName":"Tran Duc 123",
"avatar":"https://media.cdn.adultswim.com/uploads/20220927/thumbnails/2_229271558509-RickAndMorty_607_DeSmithation.png",
"phone":"0988998777",
"address":"100 Nguyen Luong Bang, Da Nang"
}
```
> [Feat] API update user

- controllers/order/orderCtrl.js
- routes/orderRouter.js
```json
{
"order_id":"63a34e3bcbf88f0004947648",
"product_id":"639e84de6be056000479ed6e"
}
```
> [Feat]  API edit order item

- .dockerignore
- controllers/order/orderCtrl.js
Return more than 2 type
```ts
}, {
createdAt: 1,
total: 1,
status: 1,
listOrderItems: 1,
updatedAt: 1,
phone: 1,
address: 1,
name: 1
});
```
> [Fix]: Return more property 🤪 

- controllers/order/orderCtrl.js
Add option
```js
.sort({ updatedAt: -1 });
```
> [Fix]: Change order by date API My order :alembic:
